spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/coupon
    username: root
    password: root
    hikari:
      max-lifetime: 30000
      connection-timeout: 3000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: 127.0.0.1
      port: 6379