global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "coupon-api"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'https://www.cwchoiit.link' ]
  - job_name: "coupon-consumer"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'https://consumer.cwchoiit.link' ]