global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "coupon-api"
    metrics_path: /actuator/prometheus
    scheme: https
    static_configs:
      - targets: [ 'www.cwchoiit.link:443' ]
  - job_name: "coupon-consumer"
    metrics_path: /actuator/prometheus
    scheme: https
    static_configs:
      - targets: [ 'consumer.cwchoiit.link:443' ]