spring:
  config:
    activate:
      on-profile: local
  application:
    name: coupon-consumer

server:
  port: 8081
management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: prometheus